### ISSUE TITLE
[Heroku] NPM ERROR

### ISSUE THREAD

**Issue by ghost** [tgcallsjs/LemonJamsBot#2]
Logs in nekobin
https://nekobin.com/juxibuxoti

**Comment by midnightmadwalk** [comment]
@UdaySriHarsha read line 27 👀

**Comment by ghost** [comment]
> @UdaySriHarsha read line 27

i know but where do i run that command
heroku dont have terminal i can use -_-

**Comment by midnightmadwalk** [comment]
@UdaySriHarsha 😐 put <code>bash</code> command in heroku console and run it and but heroku have ephemeral disk so better upgrade your package. https://devcenter.heroku.com/articles/nodejs-support

**Comment by ghost** [comment]
ohh via the console
sure, closing this issue then
