### ISSUE TITLE
Please add searching song by name

### ISSUE THREAD

**Issue by rebizzz** [tgcallsjs/LemonJamsBot#3]
Hello there I want that the bot can play song by name he is some code see if it can help you
```
def downloadMusic(file_name, link):
	ydl_opts = {
		'outtmpl': './'+file_name,
		'format': 'bestaudio/best',
		'postprocessors': [{
			'key': 'FFmpegExtractAudio',
			'preferredcodec': 'mp3',
			'preferredquality': '256',
		}],
		'prefer_ffmpeg': True
	}

	with youtube_dl.YoutubeDL(ydl_opts) as tg:
		info_dict = tg.extract_info(link, download=False)

**Comment by vrumger** [comment]
It's possible to add, but have you tried using [@vid](https://t.me/vid) on Telegram to search?

**Comment by rebizzz** [comment]
Yes i tried but it'll be more easy

And it'll consume less space by downloading set to false and using buildpack for faster playing

@AndrewLaneX

**Comment by rebizzz** [comment]
Can you please add the feature?

**Comment by vrumger** [comment]
If someone would like to open a pull request, I can merge it, but I personally won't.

**Comment by rebizzz** [comment]
Ok I'll try it

**Comment by vrumger** [comment]
How's https://github.com/tgcallsjs/LemonJamsBot/commit/3997e81139a61985734818868662d6f8e9721c05?

**Comment by vrumger** [comment]
Can I consider this resolved?

**Comment by rebizzz** [comment]
Yes, it is.
